### ISSUE TITLE
Q: nested factory

### ISSUE THREAD

**Issue by basz** [NullVoxPopuli/ember-resources#1044]
Are composited factories allowed?

Can't get them to work... Displayes 5° (default value) nothing else, but when i use the ExtruderResource directly it does work...

```ts
const ExtruderResource = resourceFactory((printerManager: PrinterManager) => {
  return resource(({ on }) => {
    const lastMessage = cell<number>(5);

    printerManager.on('statusUpdate', (status) => {
      const { extruder } = status;

      if (extruder) {
        lastMessage.set(extruder.temperature);
      }
    });

    on.cleanup(() => {});

    return () => {
      return lastMessage.current;
    };
  });
});

export const ExtruderCurrentTemperature = resourceFactory((printerManager: PrinterManager) => {
  return resource(({ on, use }) => {
    const extruder = use(ExtruderResource(printerManager));

    console.log(extruder.current);

    // const temperature = extruder.current;
    // const temp = cell<number>(temperature);

    //on.cleanup(() => {});

    return () => {
      return !isNaN(extruder.current) ? `${extruder.current}°` : '-';
    };
  });
});
```

**Comment by NullVoxPopuli** [comment]
> Are composited factories allowed?

they are, `resourceFactory` is a pass-through / no-op utility that is a consequence of current limitations in ember's helper-manager system.

> ExtruderCurrentTemperature

This looks like an exciting project!!! 3d printer stuff?

> Can't get them to work...

Are you using at least 6.4.0? the release notes have an example similar to what you're trying to achieve:

https://github.com/NullVoxPopuli/ember-resources/releases/tag/ember-resources%406.4.0


Any chance you can simulate this example in the REPL? / https://limber.glimdown.com?

**Comment by NullVoxPopuli** [comment]
ah!

`.current` can't be accessed within the `resource` main body because it would invalidate the whole resource each change (which is why it's safe to access in the `Formula` arrow fn):

[fixed](https://limber.glimdown.com/edit?c=FAAzHMCsGcAIBsCWA3ApsRBbADgewE4AusAwrjrgHaqXEBm%2B5sA5AALhKaar4D0AxuTzVazANzAMFIrADesfqnjwANLHypouAK75FajVt2KAYgEN%2BhAgE9YAX1gMmzVJgBGPALSGdezeMlBSmhiAFEAD0J8bQATHgAlTV9FWABedSTjVHNLGwAKPIBKNIA%2BOWBYDMJdSgyjPwL5Knti1LLZCsqFKhCEMxCAWU1oM3BUNIUleCKJTsqg3sRaHmQzeAnoVEIASWX8Vemi0vKuroXieVRI6Lj8ewnZK6jYngAuWAGzQgALADp8MyUGLkIp2WanSqIOiwPJPG48YodCFdeD9QhDaAjMa-TaEWHXF74QoSZF2Ob2NQARgADLTieTyVRfvx4KhAdpsAVWmUWWz8LtCCs1nkloL9mtCvTyRpqvhakc2icITKan1BsNRqhmboNLQSV0wZ07PTjeDzrAIs9biQdTRCAAVVzYHhfXTjdI%2BLI5Kz4axc45Iqqqz0NPJNShqbSbFoB8nmuGExL1FLpKOoPKW%2BH4JPJdOS-XI6VbVUK9rkyoquWwBO3HNZbX4XXEAD8zZYngCp0NlVNwF7wCueBkcToZm08GILP6cAAIq5cNXIjQYnAyBQRBdOgAeQU4VGCkrkrcxFAKVGY1IAIjcBFusGwngALLBwPhEDEX2YH4-L4fkSeNEsWA01gAB3AgAGtoHeWRZEzRNMj8Ow7C3Nx8EPctugoaBEEFD9KFwQgYLgglrVtWhHRwF1ZVQZCj14E9kD-WAt14XdsH3VBDzJMAQGAIA&format=glimdown)

**Comment by basz** [comment]
ah i see. makes sense... this is intricate...

one question, why would each resource show a different random number? it's the same resource?

**Comment by NullVoxPopuli** [comment]
> one question, why would each resource show a different random number? it's the same resource?

there are two instance of it, so different randomness for each one

**Comment by basz** [comment]
it seems ok to use in it return function... using another cell to 'memorize' the received payload

[repl](https://limber.glimdown.com/edit?c=FAAzHMCsGcAIBsCWA3ApsRBbADgewE4AusAwrjrgHaqXEBm%2B5sA5AALhKaar4D0AxuTzVazANzAMFIrADesfqnjwANLHypouAK75FajVt2KAYgEN%2BhAgE9YAX1gMmzVJgBGPALSGdezeMlgQUpoYgAFfERaHgBlQjNCaAAlTV9FWABedVTjVHNLGwAKQoBKTIA%2BOWBYbMJdSmyjP2L5KnsyjMrZapqFKlCEM1CAWU1oM3BUTIUleFKJHprggajCHmQzeGnoVEIASWj8DbnSiqre3t5eWDNHRHgaM25YTDNbQWeom7htSgATVB0KKoP6wAA%2BsEo2mU4NgoUilHAi16D3o90ezyyvwBQOofwkFxq0AA7ohCPwABawQqEfDaVBlbqE3r8IZTYYJCkAOnwZn%2B5FOlQADFyAKwALmRzKBD0oTymWRAMtQABJZIUOYRubz%2BZhSgAqACMQpNQpKXKsJkQAA8QYUzXYQATmb03BozABrZ3M1k7WCa7V8v4CsrCsWSl29ZVyzGQ6Hwb0ut2oT2Jmp2STMqV9ELEeTYBFrfAAfVCCTgDiysgLqx4pfiiXFcmj8rsdgWzMQdGpNcO9fLjOzNXgQ0Io2g40mXJ2hEKvaL-cSJTT9mRdjUxpNy%2BRyKoXP4Dz52mwxQ6lQPKfwByLx0KtaOmxK2%2BRGjq%2BAap0650Jr-qgxGYwTKg%2B66BotCJu2PR2Nu0EdssxAAKLWrS2gAvgJCgTQhAACquNgPAJLoCqNGkeQWFY%2BDWKeZxMrUf4%2BLkLSwFQajaH60E0ci8GwKgyF0mhKRNOkWI7IUET3nE5aCaRpTbhc3EjqEVqyvK0yKMohRQsoz6Rr%2B77Ume36RtxsgttwlY8XxqE8NJuQgfgYHEAA-E5ciQUOvRdtSZlTAAhBkWL-ICwJ-IOkYXIphDKRiwH8JhtDTD5K4XBmHlEqS5JUoUkXRTGsXxYQYXhUsbJxsoEbFb0ekNMwngBJVrrul6aUsqV2LBXiFUNdVLDUGg%2BD1Q1sDJqmLU1DiZjQoQXWVT1OXonl9mOclvQZilzqwcAm3ALxeAyBNU0KIpcAACKuLgllrP8cBkBQIh5j0AA8aw4COazlMij1-CgR1DNAGQAERuAQaGwNgngACywOAkSguAZjgxDAMfdmcUOVhdwPE2siyEhKFoRh6O0LhOAEW%2BqBtp9vDfcgH01I9vAvdgb2oB9GZgCAwBAA&format=glimdown)

thx again!

**Comment by NullVoxPopuli** [comment]
>  I do not see any sync or setup method on the ResourceApi (on)?

Yeah, we can't have it in ember. :(
Have to wait until starbeam apis are available.


Some more info here: https://github.com/NullVoxPopuli/ember-resources/issues/1012
