### ISSUE TITLE
Cancelling requests in `trackedFunction`

### ISSUE THREAD

**Issue by swastik** [NullVoxPopuli/ember-resources#664]
Hey there! Thanks for this great addon. 😄 

I have a question. Let's say we have a `trackedFunction` like so:

```
userLoader = trackedFunction(this, async () => {
  return fetch(`/users/${this.args.id}`)
})
```

… and I have a list of users. I can move between them, I'm expecting the latest user to be loaded. However, it seems like if a request takes longer than one after it, we end up with the wrong value.

For example:

```
click user 1 → takes 200ms to load → shows user 1
click user 2 → takes 1000ms to load
click user 3 → takes 200ms to load → shows user 3

… user 2 loads and returns at this point
```

This is on v4.10.0 of the addon. For `trackedFunction`, is there a way to _cancel_ previous loaders / requests? We could use something custom or use a task, but I'd love to know if anyone has any other ideas (or if I'm understanding anything wrong here!). Thanks!

**Comment by NullVoxPopuli** [comment]
Cancellation is out of scope for resources and trackedFunction, but the behavior you describe sounds like a bug. Is your snipped all the code? Something is fishy, i think, because fetch returns a Response object.

Also, you may want to look at the RemoteData resource, which automatically cancels fetch using AbortController.
https://ember-resources.pages.dev/functions/util_remote_data.RemoteData

**Comment by swastik** [comment]
Thanks for the response! No, there's quite a lot more code there, but [here's a minimal reproduction](https://github.com/swastik/ember-resources-tracked-function/blob/main/app/components/users-list.js).

I've added an artificial delay for user 2's response here. If I click user 2, then user 3, I'd expect user 3 to be the current user, but user 2 ends up replacing it.

https://user-images.githubusercontent.com/1569205/198054962-33da95af-9ef0-418e-9967-141b141cc79d.mp4

Let me know if I'm doing something wrong! 😄

**Comment by NullVoxPopuli** [comment]
Looks like a bug to me! Thanks for reporting! And providing that repro repo! That's helpful. I'll need to pull this in to the test suite and debug to see what's going on.

As always, PRs welcowe, i don't have consistent computer access atm. On vacation and such. :)

**Comment by swastik** [comment]
I couldn't get the addon building locally, but I tried debugging my repro. Here's what I've found so far: for a long running promise, we get to [this line of code](https://github.com/NullVoxPopuli/ember-resources/blob/v4.10.0/ember-resources/src/deprecated-in-v4/resources/function-runner.ts#L67) which seems to set the secret value and notifies others.

I was expecting it to return early [_just above_](https://github.com/NullVoxPopuli/ember-resources/blob/v4.10.0/ember-resources/src/deprecated-in-v4/resources/function-runner.ts#L63-L65) but maybe it doesn't because it's a lifecycle resource and hence isn't torn down? If I manually invalidate the long running promise and return early, it works, but I'm not sure that's the right approach.

The version I got working was something like this:

```ts
class TrackedFunctionRunner extends LifecycleResource {
  revision = 0;

  get value() {
    return get(this, SECRET_VALUE);
  }

  setup() {
    this.revision += 1;
    waitForPromise(this[RUNNER]());
  }

  update() {
    this.revision += 1;
    waitForPromise(this[RUNNER]());
  }

  async [RUNNER]() {
    <…>

    let { revision } = this;
    let previousValue = this[SECRET_VALUE];
    let value = fn(previousValue, ...[]);

    value = await Promise.resolve(value);

    // If the revision changed while we were resolving the promise, return early
    if (isDestroying(this) || isDestroyed(this) || revision !== this.revision) {
      return;
    }

    this[SECRET_VALUE] = this._currentValue;
    notifyPropertyChange(this, SECRET_VALUE);
  }
}
```

**Comment by NullVoxPopuli** [comment]
Is the issue present with the util import of tracked-function'? it's implementation switched to using a function-based resource, which may have resolved this -- here: https://github.com/NullVoxPopuli/ember-resources/blob/v4.10.0/ember-resources/src/util/function.ts#L78

I can def see where the bug is with v4 though -- the `SECRET_VALUE` was getting re-set with the long running promise, which I didn't realize until your working code was posted. Nice detective work!!

So, for the path forward for you/your project, can you try one of:
 - using `trackedFunction` from `ember-resources/util/function`
 - using patch-package with the changes you found to work 
 
 thanks!!

**Comment by swastik** [comment]
Thank you! Yes, the function based resource seems to work pretty well. We'll just switch to using that one for now then. 😄
